"""Pinned native capability inventory; this is descriptive, never an RPC allowlist."""

from codex_rpc import METHODS

SCHEMA_VERSION = "0.160.1"
SCHEMA_SOURCE = "openai/codex rust-v0.160.1 (d27764b82f7118f674371e6d6e76271d9d606edb)"
CONTRACT_VERSION = "0.1.0"

OBSERVE_METHODS = frozenset(
    {
        "account/rateLimits/read",
        "account/usage/read",
        "app/list",
        "app/read",
        "hooks/list",
        "mcpServerStatus/list",
        "mcpServer/resource/read",
        "model/list",
        "modelProvider/capabilities/read",
        "plugin/list",
        "plugin/read",
        "server/diagnostics",
        "skills/list",
        "thread/backgroundTerminals/list",
        "thread/attachment/list",
        "thread/goal/get",
        "thread/items/list",
        "thread/list",
        "thread/loaded/list",
        "thread/read",
        "thread/queue/list",
        "thread/search",
        "thread/searchOccurrences",
        "thread/turns/list",
        "thread/timeline/list",
        "threadSection/list",
    }
)
OPERATOR_CONTROL_METHODS = frozenset(
    {
        "mcpServer/tool/call",
        "review/start",
        "thread/archive",
        "thread/attachment/add",
        "thread/attachment/remove",
        "thread/backgroundTerminals/terminate",
        "thread/compact/start",
        "thread/delete",
        "thread/fork",
        "thread/goal/clear",
        "thread/goal/set",
        "thread/inject_items",
        "thread/metadata/update",
        "thread/name/set",
        "thread/queue/add",
        "thread/queue/delete",
        "thread/queue/reorder",
        "thread/queue/start",
        "thread/queue/update",
        "thread/resume",
        "thread/revert",
        "thread/settings/update",
        "thread/start",
        "thread/unarchive",
        "thread/section/move",
        "threadSection/create",
        "threadSection/delete",
        "threadSection/update",
        "turn/interrupt",
        "turn/settings/update",
        "turn/start",
        "turn/steer",
    }
)
CAS_ADDITIVE_METHODS = frozenset(
    {
        "thread/archive",
        "thread/attachment/add",
        "thread/attachment/list",
        "thread/attachment/remove",
        "app/read",
        "thread/section/move",
        "thread/compact/start",
        "thread/delete",
        "thread/fork",
        "thread/inject_items",
        "thread/metadata/update",
        "thread/name/set",
        "thread/queue/add",
        "thread/queue/delete",
        "thread/queue/list",
        "thread/queue/reorder",
        "thread/queue/start",
        "thread/queue/update",
        "account/rateLimits/read",
        "account/usage/read",
        "app/list",
        "hooks/list",
        "mcpServer/resource/read",
        "mcpServer/tool/call",
        "plugin/list",
        "plugin/read",
        "review/start",
        "skills/list",
        "thread/backgroundTerminals/list",
        "thread/backgroundTerminals/terminate",
        "thread/revert",
        "thread/search",
        "thread/searchOccurrences",
        "thread/timeline/list",
        "threadSection/list",
        "threadSection/create",
        "threadSection/update",
        "threadSection/delete",
        "thread/unarchive",
    }
)


def classify_exposed_method(method: str) -> str | None:
    if method in OBSERVE_METHODS:
        return "OBSERVE"
    if method in OPERATOR_CONTROL_METHODS:
        return "OPERATOR_CONTROL"
    return None


def validate_exposed_methods(methods: frozenset[str] | set[str]) -> None:
    unclassified = methods - OBSERVE_METHODS - OPERATOR_CONTROL_METHODS
    if unclassified:
        raise ValueError(
            "Exposed native methods lack an explicit classification: "
            + ", ".join(sorted(unclassified))
        )


validate_exposed_methods(METHODS)

FAMILIES = (
    {
        "classification": "OBSERVE",
        "status": "supported",
        "methods": sorted(OBSERVE_METHODS),
        "reason": "Typed, target-scoped reads exposed in the operator profile.",
    },
    {
        "classification": "OPERATOR_CONTROL",
        "status": "supported",
        "methods": sorted(OPERATOR_CONTROL_METHODS),
        "reason": "Typed control methods exposed in the operator profile.",
    },
    {
        "classification": "EXPERIMENTAL",
        "status": "partially_supported",
        "methods": [
            "account/bedrock/discover",
            "account/bedrock/setup",
            "app/read",
            "collaborationMode/list",
            "environment/add",
            "environment/info",
            "environment/status",
            "fuzzyFileSearch/sessionStart",
            "fuzzyFileSearch/sessionStop",
            "fuzzyFileSearch/sessionUpdate",
            "mcpServer/event/stream/start",
            "mcpServer/event/stream/stop",
            "memory/reset",
            "memory/status",
            "mock/experimentalMethod",
            "plugin/search",
            "process/kill",
            "process/resizePty",
            "process/spawn",
            "process/writeStdin",
            "project/create",
            "project/delete",
            "project/import",
            "project/list",
            "project/move",
            "project/read",
            "project/update",
            "remoteControl/client/list",
            "remoteControl/client/revoke",
            "remoteControl/disable",
            "remoteControl/enable",
            "remoteControl/pairing/start",
            "remoteControl/pairing/status",
            "remoteControl/status/read",
            "rollout/compress",
            "server/diagnostics",
            "thread/backgroundTerminals/clean",
            "thread/backgroundTerminals/list",
            "thread/backgroundTerminals/terminate",
            "thread/decrement_elicitation",
            "thread/increment_elicitation",
            "thread/memoryMode/set",
            "thread/queue/add",
            "thread/queue/delete",
            "thread/queue/list",
            "thread/queue/reorder",
            "thread/queue/start",
            "thread/queue/update",
            "thread/realtime/appendAudio",
            "thread/realtime/appendSpeech",
            "thread/realtime/appendText",
            "thread/realtime/listVoices",
            "thread/realtime/start",
            "thread/realtime/stop",
            "thread/search",
            "thread/searchOccurrences",
            "thread/settings/update",
            "thread/timeline/list",
            "turn/settings/update",
            "userVerification/cancel",
            "userVerification/delete",
            "userVerification/enroll",
            "userVerification/status",
            "userVerification/verify",
        ],
        "exposed_methods": [
            "app/read",
            "server/diagnostics",
            "thread/backgroundTerminals/list",
            "thread/backgroundTerminals/terminate",
            "thread/queue/add",
            "thread/queue/delete",
            "thread/queue/list",
            "thread/queue/reorder",
            "thread/queue/start",
            "thread/queue/update",
            "thread/search",
            "thread/searchOccurrences",
            "thread/settings/update",
            "thread/timeline/list",
            "turn/settings/update",
        ],
        "reason": "Experimental protocol methods require explicit CAS mappings; unexposed methods are never inferred from daemon support.",
        "unexposed_reason": "No CAS request/response contract or regression fixture is defined for a hidden experimental method.",
    },
    {
        "classification": "ADMIN",
        "status": "not_exposed",
        "methods": [
            "account/gatewayOAuth/login",
            "account/bedrock/setup",
            "account/gatewayOAuth/cancel",
            "account/login/start",
            "account/login/cancel",
            "account/logout",
            "account/chatgptAuthTokens/refresh",
            "account/rateLimitResetCredit/consume",
            "account/sendAddCreditsNudgeEmail",
            "command/exec",
            "command/exec/resize",
            "command/exec/terminate",
            "command/exec/write",
            "config/batchWrite",
            "config/mcpServer/reload",
            "config/value/write",
            "environment/add",
            "fs/copy",
            "fs/createDirectory",
            "fs/remove",
            "fs/unwatch",
            "fs/watch",
            "fs/writeFile",
            "experimentalFeature/enablement/set",
            "environment/info",
            "environment/status",
            "marketplace/add",
            "marketplace/remove",
            "marketplace/upgrade",
            "memory/reset",
            "mcpServer/oauth/login",
            "plugin/share/save",
            "plugin/share/updateTargets",
            "plugin/share/checkout",
            "plugin/share/delete",
            "plugin/reconcile",
            "plugin/install",
            "plugin/uninstall",
            "process/spawn",
            "process/writeStdin",
            "process/kill",
            "process/resizePty",
            "remoteControl/enable",
            "remoteControl/disable",
            "remoteControl/status/read",
            "remoteControl/client/revoke",
            "remoteControl/pairing/start",
            "remoteControl/pairing/status",
            "remoteControl/client/list",
            "skills/config/write",
            "skills/extraRoots/set",
            "thread/approveGuardianDeniedAction",
            "thread/backgroundTerminals/clean",
            "thread/shellCommand",
            "project/create",
            "project/import",
            "project/update",
            "project/move",
            "project/delete",
            "rollout/compress",
            "windowsSandbox/setupStart",
        ],
        "reason": "Host, credential, package, process, and configuration mutations are absent from the ordinary operator profile; no caller-selectable elevation exists.",
    },
    {
        "classification": "CALLBACK",
        "status": "unsupported",
        "methods": [
            "item/commandExecution/requestApproval",
            "item/fileChange/requestApproval",
            "item/permissions/requestApproval",
            "item/tool/requestUserInput",
            "mcpServer/elicitation/request",
            "item/tool/call",
        ],
        "reason": "The native callback is tied to the originating bidirectional WebSocket. CAS closes that connection at action completion and has no durable/resumable fenced-response protocol; it fails closed and never auto-approves.",
    },
    {
        "classification": "DEFERRED/UNSUPPORTED",
        "status": "not_exposed",
        "methods": [
            "account/gatewayOAuth/read",
            "account/read",
            "account/workspaceMessages/read",
            "account/sendAddCreditsNudgeEmail",
            "app/installed",
            "config/read",
            "configRequirements/read",
            "experimentalFeature/list",
            "permissionProfile/list",
            "externalAgentConfig/detect",
            "externalAgentConfig/import",
            "externalAgentConfig/import/recordHistory",
            "externalAgentConfig/import/readHistories",
            "fs/getMetadata",
            "fs/readDirectory",
            "fs/readFile",
            "feedback/upload",
            "getAuthStatus",
            "getConversationSummary",
            "gitDiffToRemote",
            "fuzzyFileSearch",
            "plugin/skill/read",
            "plugin/installed",
            "plugin/share/list",
            "project/list",
            "project/read",
            "thread/unsubscribe",
            "windowsSandbox/readiness",
        ],
        "reason": "Native methods are present in the pinned schema but do not yet have reviewed typed CAS request/response mappings and regression coverage.",
    },
    {
        "classification": "PROTOCOL_BOOTSTRAP",
        "status": "required",
        "methods": ["initialize"],
        "reason": "Initialize establishes the native app-server protocol session and is not an operator capability.",
    },
)


def inventory(native_version: str | None) -> dict:
    return {
        "native_codex_version": native_version or "unavailable",
        "native_schema_version": SCHEMA_VERSION,
        "native_schema_source": SCHEMA_SOURCE,
        "schema_request_counts": {
            "default_client_requests": 104,
            "experimental_client_requests": 167,
            "experimental_only_client_requests": 63,
        },
        "cas_contract_version": CONTRACT_VERSION,
        "server_exposure_profile": "operator",
        "admin_enabled": False,
        "families": [
            {
                **family,
                "methods": list(family["methods"]),
                **(
                    {"exposed_methods": list(family["exposed_methods"])}
                    if "exposed_methods" in family
                    else {}
                ),
            }
            for family in FAMILIES
        ],
    }
